/* 🤖 this file was generated by svg-to-ts */
export const pixelBgBeach: {
  name: 'bg_beach';
  data: string;
} = {
  name: 'bg_beach',
  data: `<path style="fill:#32aaff;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M0 0h84.667v37.042H0z"/><path style="fill:#e9ddb7;fill-opacity:1;fill-rule:evenodd;stroke-width:.751177" d="M40 110v10H30v10H20v10H0v180h320V140H110v-10H90v-10H70v-10H40z" transform="scale(.26458)"/><path style="fill:#32aaff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M210 140v10h20v10h20v10h30v-10h10v-10h10v-10h-90z" transform="scale(.26458)"/>`
};
export const pixelBgNight: {
  name: 'bg_night';
  data: string;
} = {
  name: 'bg_night',
  data: `<path style="fill:#110019;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M0 0h84.667v84.667H0z"/>`
};
export const pixelBgSand: {
  name: 'bg_sand';
  data: string;
} = {
  name: 'bg_sand',
  data: `<path style="fill:#e9ddb7;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M0 0h84.667v84.667H0z"/>`
};
export const pixelBgSkyblue: {
  name: 'bg_skyblue';
  data: string;
} = {
  name: 'bg_skyblue',
  data: `<path style="fill:#8ef5ff;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M0 0h84.667v84.667H0z"/>`
};
export const pixelBgSpace: {
  name: 'bg_space';
  data: string;
} = {
  name: 'bg_space',
  data: `<path style="fill:#110019;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M0 0h84.667v84.667H0z"/><path style="fill:#cdfadd;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 10v10h10V10h-10zM20 20v10h10V20H20zm200 0v10h10V20h-10zm70 10v10h10V30h-10zM70 40v10H50v10h20v10h10V60h20V50H80V40H70zm120 0v10h10V40h-10zm70 20v20h-10v10h10v20h10V90h10V80h-10V60h-10zM140 80v10h10V80h-10zm-90 30v10H40v10h10v10h10v-10h10v-10H60v-10H50zm120 0v10h10v-10h-10zm120 20v10h-10v10h10v10h10v-10h10v-10h-10v-10h-10zm-60 30v10h10v-10h-10zM40 170v10h10v-10H40zm30 20v10h10v-10H70zm210 20v10h10v-10h-10zM80 250v10h10v-10H80zm160 20v10h10v-10h-10zM10 290v10h10v-10H10zm260 0v10h10v-10h-10z" transform="scale(.26458)"/>`
};
export const pixelBgWater: {
  name: 'bg_water';
  data: string;
} = {
  name: 'bg_water',
  data: `<path style="fill:#32aaff;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M0 0h84.667v84.667H0z"/>`
};
export type background =
  | 'bg_beach'
  | 'bg_night'
  | 'bg_sand'
  | 'bg_skyblue'
  | 'bg_space'
  | 'bg_water';
export interface MyIcon {
  name: background;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];
export const completeIconSet = [
  pixelBgBeach,
  pixelBgNight,
  pixelBgSand,
  pixelBgSkyblue,
  pixelBgSpace,
  pixelBgWater
];
