/* 🤖 this file was generated by svg-to-ts */
export const pixelBodyDefishirtBlue: {
  name: 'body_defishirt_blue';
  data: string;
} = {
  name: 'body_defishirt_blue',
  data: `<path style="fill-rule:evenodd;stroke-width:.264999;fill:#3b5cf7;fill-opacity:1" d="M23.813 55.563h37.041v29.104H23.813Z"/><path style="fill:#000;fill-rule:evenodd;stroke-width:1.00157" d="M100 230v70h20v-10h10v-50h-10v-10zm80 0v70h40v-30h-10v-10h10v-10h-10v-20zm-40 20v50h30v-50z" transform="scale(.26458)"/><path style="fill:#3b5cf7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 240v50h10v-50zm80 0v10h10v10h-10v40h20v-60zm-40 20v10h10v-10zm0 20v10h20v-10z" transform="scale(.26458)"/>`
};
export const pixelBodyDefishirtGreen: {
  name: 'body_defishirt_green';
  data: string;
} = {
  name: 'body_defishirt_green',
  data: `<path style="fill-rule:evenodd;stroke-width:.264999;fill:#00c900;fill-opacity:1" d="M23.813 55.563h37.041v29.104H23.813Z"/><path style="fill:#000;fill-rule:evenodd;stroke-width:1.00157" d="M100 230v70h20v-10h10v-50h-10v-10zm80 0v70h40v-30h-10v-10h10v-10h-10v-20zm-40 20v50h30v-50z" transform="scale(.26458)"/><path style="fill:#00c900;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 240v50h10v-50zm80 0v10h10v10h-10v40h20v-60zm-40 20v10h10v-10zm0 20v10h20v-10z" transform="scale(.26458)"/>`
};
export const pixelBodyDefishirtNavy: {
  name: 'body_defishirt_navy';
  data: string;
} = {
  name: 'body_defishirt_navy',
  data: `<path style="fill-rule:evenodd;stroke-width:.264999;fill:navy" d="M23.813 55.563h37.041v29.104H23.813Z"/><path style="fill:#fff;fill-rule:evenodd;stroke-width:1.00157" d="M100 230v70h20v-10h10v-50h-10v-10zm80 0v70h40v-30h-10v-10h10v-10h-10v-20zm-40 20v50h30v-50z" transform="scale(.26458)"/><path style="fill:navy;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 240v50h10v-50zm80 0v10h10v10h-10v40h20v-60zm-40 20v10h10v-10zm0 20v10h20v-10z" transform="scale(.26458)"/>`
};
export const pixelBodyDefishirtPink: {
  name: 'body_defishirt_pink';
  data: string;
} = {
  name: 'body_defishirt_pink',
  data: `<path style="fill-rule:evenodd;stroke-width:.264999;fill:#ff757c;fill-opacity:1" d="M23.813 55.563h37.041v29.104H23.813Z"/><path style="fill:#000;fill-rule:evenodd;stroke-width:1.00157" d="M100 230v70h20v-10h10v-50h-10v-10zm80 0v70h40v-30h-10v-10h10v-10h-10v-20zm-40 20v50h30v-50z" transform="scale(.26458)"/><path style="fill:#ff757c;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 240v50h10v-50zm80 0v10h10v10h-10v40h20v-60zm-40 20v10h10v-10zm0 20v10h20v-10z" transform="scale(.26458)"/>`
};
export const pixelBodyFoPshirtBlack: {
  name: 'body_fo_pshirt_black';
  data: string;
} = {
  name: 'body_fo_pshirt_black',
  data: `<path style="fill:#170038;fill-rule:evenodd;stroke-width:1.00157;fill-opacity:1" d="M90 210v110h140V210Z" transform="scale(.26458)"/><path style="fill:#b3b3b3;fill-opacity:1;fill-rule:evenodd;stroke-width:.867386" d="M125 220v5h-10v5h-10v10h-5v25h10v5h5v10h10v5h5v5h5v5h5v5h10v5h5v5h10v-5h5v-5h10v-5h5v-5h5v-5h5v-5h10v-10h5v-5h10v-25h-5v-10h-10v-5h-10v-5z" transform="scale(.26458)"/><path style="fill:#44128d;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 230v45h5v-25h15v-5h-15v-10h20v-5h-20zm60 0v45h5v-25h15v-5h-15v-10h15v-5zm20 5v10h5v-10zm-50 10v5h20v-5zm20 5v20h5v-20zm0 20h-20v5h20zm-20 0v-20h-5v20z" transform="scale(.26458)"/>`
};
export const pixelBodyFoPshirtLightblue: {
  name: 'body_fo_pshirt_lightblue';
  data: string;
} = {
  name: 'body_fo_pshirt_lightblue',
  data: `<path style="fill:#32abc9;fill-rule:evenodd;stroke-width:1.00157;fill-opacity:1" d="M90 210v110h140V210Z" transform="scale(.26458)"/><path style="fill:#b3b3b3;fill-opacity:1;fill-rule:evenodd;stroke-width:.867386" d="M125 220v5h-10v5h-10v10h-5v25h10v5h5v10h10v5h5v5h5v5h5v5h10v5h5v5h10v-5h5v-5h10v-5h5v-5h5v-5h5v-5h10v-10h5v-5h10v-25h-5v-10h-10v-5h-10v-5z" transform="scale(.26458)"/><path style="fill:#44128d;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 230v45h5v-25h15v-5h-15v-10h20v-5h-20zm60 0v45h5v-25h15v-5h-15v-10h15v-5zm20 5v10h5v-10zm-50 10v5h20v-5zm20 5v20h5v-20zm0 20h-20v5h20zm-20 0v-20h-5v20z" transform="scale(.26458)"/>`
};
export const pixelBodyFoPshirtOrange: {
  name: 'body_fo_pshirt_orange';
  data: string;
} = {
  name: 'body_fo_pshirt_orange',
  data: `<path style="fill:#ffb52a;fill-rule:evenodd;stroke-width:1.00200002;fill-opacity:1;stroke:none;stroke-opacity:1;stroke-miterlimit:4;stroke-dasharray:none" d="M90 210v110h140V210Z" transform="scale(.26458)"/><path style="fill:#b3b3b3;fill-opacity:1;fill-rule:evenodd;stroke-width:.867386" d="M125 220v5h-10v5h-10v10h-5v25h10v5h5v10h10v5h5v5h5v5h5v5h10v5h5v5h10v-5h5v-5h10v-5h5v-5h5v-5h5v-5h10v-10h5v-5h10v-25h-5v-10h-10v-5h-10v-5z" transform="scale(.26458)"/><path style="fill:#44128d;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 230v45h5v-25h15v-5h-15v-10h20v-5h-20zm60 0v45h5v-25h15v-5h-15v-10h15v-5zm20 5v10h5v-10zm-50 10v5h20v-5zm20 5v20h5v-20zm0 20h-20v5h20zm-20 0v-20h-5v20z" transform="scale(.26458)"/>`
};
export const pixelBodyOPshirt: {
  name: 'body_o_pshirt';
  data: string;
} = {
  name: 'body_o_pshirt',
  data: `<path style="fill-rule:evenodd;stroke-width:.264999;fill:#ff0420;fill-opacity:1" d="M23.813 55.563h37.041v29.104H23.813Z"/><path style="fill:#d40000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M155 230v20h-55v10h55v15h-5v5h5v10h-5v5h5v15h10v-15h5v-5h-5v-10h5v-5h-5v-15h55v-10h-55v-20h-10zm65 20h10v-10h-10v10zm-50 30v5h35v-5h-35zm35 0h5v-5h-5v5zm-35 15v5h30v-5h-30zm30 0h5v-5h-5v5zm-35 15v5h25v-5h-25zm25 0h5v-5h-5v5zm-35 0h-25v5h25v-5zm-25 0v-5h-5v5h5zm20-15h-30v5h30v-5zm-30 0v-5h-5v5h5zm30-15h-35v5h35v-5zm-35 0v-5h-5v5h5zm-15-30v-10H90v10h10z" transform="scale(.26458)"/><path style="fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 220v30h10v-20h20v20h10v-30h-40zm60 0v30h40v-30h-40zm10 10h20v10h-20v-10zm-70 30v10h40v-10h-40zm60 0v10h10v-10h-10z" transform="scale(.26458)"/><path style="fill:#b3b3b3;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 250v10h10v-10h-10zm30 0v10h10v-10h-10zm30 0v10h10v-10h-10z" transform="scale(.26458)"/>`
};
export const pixelBodyPoolyBot: {
  name: 'body_pooly_bot';
  data: string;
} = {
  name: 'body_pooly_bot',
  data: `<path style="fill:gray;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M23.813 55.563h37.042v29.104H23.813z"/><path style="fill:#404040;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M100 220v10h10v-10zm110 0v10h10v-10zm-80 30v10h10v-10zm50 0v10h10v-10zm-50 30v10h10v-10zm50 0v10h10v-10zm-80 20v10h10v-10zm110 0v10h10v-10z" transform="scale(.26458)"/>`
};
export const pixelBodyPooly: {
  name: 'body_pooly';
  data: string;
} = {
  name: 'body_pooly',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M23.813 55.563h37.042v29.104H23.813z"/>`
};
export const pixelBodyTornadoshirt: {
  name: 'body_tornadoshirt';
  data: string;
} = {
  name: 'body_tornadoshirt',
  data: `<path style="fill:#000;fill-rule:evenodd;stroke-width:.276782" d="M23.813 52.917h37.041v31.75H23.813Z"/><path style="fill:#69feba;fill-opacity:1;fill-rule:evenodd;stroke-width:1.22667" d="M160 200v10h-10v10h-10v10h-10v20h-10v-30h-10v10h-10v30h10v10h10v10h10v10h20v10h-30v10h10v10h30v-10h10v-10h10v-10h10v-20h10v30h10v-10h10v-30h-10v-10h-10v-10h-10v-10h-20v-10h30v-10h-10v-10h-30zm40 20v10h10v-10h-10zm0 80h-10v10h10v-10zm-80 0v-10h-10v10h10zm0-80h10v-10h-10v10zm30 20h20v10h10v20h-10v10h-20v-10h-10v-20h10v-10z" transform="scale(.26458)"/>`
};

export type body =
  | 'body_defishirt_blue'
  | 'body_defishirt_green'
  | 'body_defishirt_navy'
  | 'body_defishirt_pink'
  | 'body_fo_pshirt_black'
  | 'body_fo_pshirt_lightblue'
  | 'body_fo_pshirt_orange'
  | 'body_o_pshirt'
  | 'body_pooly_bot'
  | 'body_pooly'
  | 'body_tornadoshirt';
export interface MyIcon {
  name: body;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];
export const completeIconSet = [
  pixelBodyDefishirtBlue,
  pixelBodyDefishirtGreen,
  pixelBodyDefishirtNavy,
  pixelBodyDefishirtPink,
  pixelBodyFoPshirtBlack,
  pixelBodyFoPshirtLightblue,
  pixelBodyFoPshirtOrange,
  pixelBodyOPshirt,
  pixelBodyPoolyBot,
  pixelBodyPooly,
  pixelBodyTornadoshirt
];
