/* 🤖 this file was generated by svg-to-ts */
export const pixelFeetPoolyLegsleft: {
  name: 'feet_pooly_legsleft';
  data: string;
} = {
  name: 'feet_pooly_legsleft',
  data: `<path style="fill:#ffb70f;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M20 290v20h10v-20H20zm10 20v10h60v-10H50v-20H40v20H30zM50 270v10h10v-10H50zm10 10v10h30v-10H80v-10H70v10H60z" transform="scale(.26458)"/>`
};
export const pixelFeetPoolyLegsright: {
  name: 'feet_pooly_legsright';
  data: string;
} = {
  name: 'feet_pooly_legsright',
  data: `<path style="fill:#ffb70f;fill-rule:evenodd;stroke-width:1.00157" d="M240 270v10h-10v10h30v-10h-10v-10h-10zm20 10h10v-10h-10v10z" transform="scale(.26458)"/><path style="fill:#ffb70f;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M270 290v20h-40v10h60v-10h-10v-20h-10zm20 20h10v-20h-10v20z" transform="scale(.26458)"/>`
};
export const pixelFeetSitting: {
  name: 'feet_sitting';
  data: string;
} = {
  name: 'feet_sitting',
  data: `<path style="fill:#ffb70f;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M20 290v20h10v-20zm10 20v10h60v-10H50v-20H40v20zm240-20v20h-40v10h60v-10h-10v-20zm20 20h10v-20h-10z" transform="scale(.26458)"/><path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 300v10h10v-10H80zm150 0v10h10v-10h-10z" transform="scale(.26458)"/>`
};
export type bodyLower =
  | 'feet_pooly_legsleft'
  | 'feet_pooly_legsright'
  | 'feet_sitting';
export interface MyIcon {
  name: bodyLower;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];
export const completeIconSet = [
  pixelFeetPoolyLegsleft,
  pixelFeetPoolyLegsright,
  pixelFeetSitting
];
