/* 🤖 this file was generated by svg-to-ts */
export const pixelHatAccBeanieBlue: {
  name: 'hat_acc_beanie_blue';
  data: string;
} = {
  name: 'hat_acc_beanie_blue',
  data: `<path style="opacity:1;fill:#0d26cc;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M21.167 13.23h39.687v5.29H21.167z"/><path style="opacity:1;fill:#3b5cf7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 10v10h-20v10h-10v10H90v10h10v10h10V50h10v10h10V50h10v10h10V50h10v10h10V50h10v10h10V50h10v10h10V50h10V40h-10V30h-10V20h-20V10Z" transform="scale(.26458)"/><path style="opacity:1;fill:#0d26cc;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M39.688 2.646h2.645v2.646h-2.645Z"/>`
};
export const pixelHatAccBeanieGreen: {
  name: 'hat_acc_beanie_green';
  data: string;
} = {
  name: 'hat_acc_beanie_green',
  data: `<path style="opacity:1;fill:#099516;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M21.167 13.23h39.687v5.29H21.167z"/><path style="opacity:1;fill:#00c900;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 10v10h-20v10h-10v10H90v10h10v10h10V50h10v10h10V50h10v10h10V50h10v10h10V50h10v10h10V50h10v10h10V50h10V40h-10V30h-10V20h-20V10Z" transform="scale(.26458)"/><path style="opacity:1;fill:#099516;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M39.688 2.646h2.645v2.646h-2.645Z"/>`
};
export const pixelHatAccBeaniePink: {
  name: 'hat_acc_beanie_pink';
  data: string;
} = {
  name: 'hat_acc_beanie_pink',
  data: `<path style="opacity:1;fill:#f95c62;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M21.167 13.23h39.687v5.29H21.167z"/><path style="opacity:1;fill:#ff757c;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 10v10h-20v10h-10v10H90v10h10v10h10V50h10v10h10V50h10v10h10V50h10v10h10V50h10v10h10V50h10v10h10V50h10V40h-10V30h-10V20h-20V10Z" transform="scale(.26458)"/><path style="opacity:1;fill:#f95c62;fill-rule:evenodd;stroke-width:.264999;fill-opacity:1" d="M39.688 2.646h2.645v2.646h-2.645Z"/>`
};
export const pixelHatAccCapBlue: {
  name: 'hat_acc_cap_blue';
  data: string;
} = {
  name: 'hat_acc_cap_blue',
  data: `<path style="opacity:1;fill:#3b5cf7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 20v10h-20v10h-10v10H90v20h190V50h-30v10h-20V50h-10V40h-10V30h-20V20Z" transform="scale(.26458)"/>`
};
export const pixelHatAccCapGreen: {
  name: 'hat_acc_cap_green';
  data: string;
} = {
  name: 'hat_acc_cap_green',
  data: `<path style="opacity:1;fill:#00c900;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 20v10h-20v10h-10v10H90v20h190V50h-30v10h-20V50h-10V40h-10V30h-20V20Z" transform="scale(.26458)"/>`
};
export const pixelHatAccCapPink: {
  name: 'hat_acc_cap_pink';
  data: string;
} = {
  name: 'hat_acc_cap_pink',
  data: `<path style="opacity:1;fill:#ff757c;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 20v10h-20v10h-10v10H90v20h190V50h-30v10h-20V50h-10V40h-10V30h-20V20Z" transform="scale(.26458)"/>`
};
export const pixelHatAccCowboyhatBrown: {
  name: 'hat_acc_cowboyhat_brown';
  data: string;
} = {
  name: 'hat_acc_cowboyhat_brown',
  data: `<path style="opacity:1;fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 10v10h-10v20H90v20H80V50H70v20h180V60h-20V40h-10V30h-10V20h-40v10h-30V20h-10V10Z" transform="scale(.26458)"/>`
};
export const pixelHatAccCowboyhatTan: {
  name: 'hat_acc_cowboyhat_tan';
  data: string;
} = {
  name: 'hat_acc_cowboyhat_tan',
  data: `<path style="opacity:1;fill:#ac9393;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 10v10h-10v20H90v20H80V50H70v20h180V60h-20V40h-10V30h-10V20h-40v10h-30V20h-10V10Z" transform="scale(.26458)"/>`
};
export const pixelHatAccEgghead: {
  name: 'hat_acc_egghead';
  data: string;
} = {
  name: 'hat_acc_egghead',
  data: `<path style="opacity:1;fill:#e5e0c9;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 10v10h-20v10h-10v10H90v10H80v30h10V70h20v20h10v10h10V80h10V70h20v10h10v10h10V70h10v10h10V70h20v10h10v10h10V80h10V50h-10V40h-10V30h-10V20h-20V10Z" transform="scale(.26458)"/><path style="opacity:1;fill:#908554;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 30v10h10V30Zm10 10v20h10V40Zm10 20v10h10V60Zm30-30v20h10V30Zm10 20v20h10V50Zm10 0h10V40h-10zm30 0v10h20V50Zm0 10h-10v10h10zm-120 0v10h10V60Z" transform="scale(.26458)"/>`
};
export const pixelHatAccGigabrain: {
  name: 'hat_acc_gigabrain';
  data: string;
} = {
  name: 'hat_acc_gigabrain',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M100 0v10H90v10H80v40h10v10h140V60h10V20h-10V10h-10V0h-50v10h-20V0Z" transform="scale(.26458)"/><path style="fill:#57007f;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 0v10h10V0Zm10 10v30h10V30h10V20h-10V10Zm20 20v10h10V30Zm40-30v20h10V0Zm0 20h-10v10h10zm20 10v10h-10v10h30V40h-10V30Zm20 20v10h10V50ZM90 40v10h10V40Zm10 10v20h10V50Zm60 0v10h10V50Zm0 10h-10v10h10z" transform="scale(.26458)"/>`
};
export const pixelHatAccKing: {
  name: 'hat_acc_king';
  data: string;
} = {
  name: 'hat_acc_king',
  data: `<path style="opacity:1;fill:#ffd800;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M70 10v40h10v20h150V50h10V10h-10v10h-10v20h-10V20h-10V10h-10v10h-10v20h-10V20h-10V10h-10v10h-10v20h-10V20h-10V10h-10v10h-10v20H90V20H80V10Z" transform="scale(.26458)"/><path style="opacity:1;mix-blend-mode:normal;fill:#0026ff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M90 50v10h10V50Zm40 0v10h10V50Zm40 0v10h10V50Zm40 0v10h10V50Z" transform="scale(.26458)"/><path style="opacity:1;fill:#007f46;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v10h10V40Zm30 0v10h10V40Zm40 0v10h10V40Zm40 0v10h10V40Zm30 0v10h10V40Z" transform="scale(.26458)"/><path style="opacity:1;fill:red;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M70 20v10h10V20Zm40 0v10h10V20Zm40 0v10h10V20Zm40 0v10h10V20Zm40 0v10h10V20Z" transform="scale(.26458)"/>`
};
export const pixelHatAccLeprechaun: {
  name: 'hat_acc_leprechaun';
  data: string;
} = {
  name: 'hat_acc_leprechaun',
  data: `<path style="opacity:1;fill:#007f46;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M90 0v10H80v20h10v30H70v10h180V60h-20V30h10V10h-10V0Z" transform="scale(.26458)"/><path style="opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M23.813 10.583h37.041v2.646H23.813Z"/><path style="opacity:1;fill:#ffd800;fill-rule:evenodd;stroke-width:.264999" d="M50.27 7.938h7.938v7.937h-7.937z"/><path style="opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M52.917 10.583h2.645v2.646h-2.645z"/>`
};
export const pixelHatAccPowderedwig: {
  name: 'hat_acc_powderedwig';
  data: string;
} = {
  name: 'hat_acc_powderedwig',
  data: `<path style="opacity:1;fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 10v30h30V10Zm-40 30v30h30V40Zm90 0v30h30V40ZM60 80v30h30V80Zm30 50v30h30v-30zm-40 30v30h30v-30z" transform="scale(.26458)"/><path style="opacity:1;fill:#666;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M170 10v30h30V10ZM80 20v30h30V20Zm50 20v30h30V40ZM90 70v30h30V70Zm-40 40v30h30v-30zm30 50v30h30v-30z" transform="scale(.26458)"/><path style="opacity:1;fill:#b3b3b3;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M110 10v30h30V10Zm50 30v30h30V40ZM70 50v30h30V50Zm10 50v30h30v-30zm-20 90v30h30v-30z" transform="scale(.26458)"/><path style="opacity:1;fill:#d9d9d9;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M15.875 34.396h7.938v7.938h-7.938z"/><path style="opacity:1;fill:gray;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M200 20v20h10V20ZM70 30v20h10V30ZM60 60v20h10V60Zm60 10v10h20V70Zm60 0v10h20V70ZM50 90v20h10V90Zm20 50v10h10v-10z" transform="scale(.26458)"/><path style="opacity:1;fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M180 20v10h10V20ZM90 30v10h10V30Zm50 20v10h10V50Zm-40 30v10h10V80Zm-40 40v10h10v-10zm30 50v10h10v-10z" transform="scale(.26458)"/><path style="opacity:1;fill:#b3b3b3;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 20v10h10V20Zm-40 30v10h10V50Zm90 0v10h10V50ZM70 90v10h10V90Zm30 50v10h10v-10zm-40 30v10h10v-10z" transform="scale(.26458)"/><path style="opacity:1;fill:#666;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 20v10h10V20Zm50 30v10h10V50ZM80 60v10h10V60Zm10 50v10h10v-10zm-20 90v10h10v-10z" transform="scale(.26458)"/>`
};
export const pixelHatAccSnorkelBlue: {
  name: 'hat_acc_snorkel_blue';
  data: string;
} = {
  name: 'hat_acc_snorkel_blue',
  data: `<path style="opacity:1;fill:#3b5cf7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M70 0v10h20V0Zm20 30v40h10v10h10v10h30V80h-20V70h-10V60h-10V40h120v20h-10v10h-10v10h-20v10h30V80h10V70h10V30H100Zm90 50V70h-10v10Zm-10-10V60h-20v10zm-20 0h-10v10h10zm-40 60v10h20v-10z" transform="scale(.26458)"/><path style="opacity:1;fill:#0ff;fill-opacity:.75;fill-rule:evenodd;stroke-width:1.00157" d="M100 40v20h10v10h10v10h20V70h10V60h20v10h10v10h20V70h10V60h10V40Z" transform="scale(.26458)"/><path style="opacity:1;fill:#0d26cc;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M70 10v140h10v10h40v-10h10v-10H90V10Z" transform="scale(.26458)"/>`
};
export const pixelHatAccSnorkelGreen: {
  name: 'hat_acc_snorkel_green';
  data: string;
} = {
  name: 'hat_acc_snorkel_green',
  data: `<path style="opacity:1;fill:#00c900;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M70 0v10h20V0Zm20 30v40h10v10h10v10h30V80h-20V70h-10V60h-10V40h120v20h-10v10h-10v10h-20v10h30V80h10V70h10V30H100Zm90 50V70h-10v10Zm-10-10V60h-20v10zm-20 0h-10v10h10zm-40 60v10h20v-10z" transform="scale(.26458)"/><path style="opacity:1;fill:#0ff;fill-opacity:.75;fill-rule:evenodd;stroke-width:1.00157" d="M100 40v20h10v10h10v10h20V70h10V60h20v10h10v10h20V70h10V60h10V40Z" transform="scale(.26458)"/><path style="opacity:1;fill:#099516;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M70 10v140h10v10h40v-10h10v-10H90V10Z" transform="scale(.26458)"/>`
};
export const pixelHatAccSnorkelPink: {
  name: 'hat_acc_snorkel_pink';
  data: string;
} = {
  name: 'hat_acc_snorkel_pink',
  data: `<path style="opacity:1;fill:#ff757c;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M70 0v10h20V0Zm20 30v40h10v10h10v10h30V80h-20V70h-10V60h-10V40h120v20h-10v10h-10v10h-20v10h30V80h10V70h10V30H100Zm90 50V70h-10v10Zm-10-10V60h-20v10zm-20 0h-10v10h10zm-40 60v10h20v-10z" transform="scale(.26458)"/><path style="opacity:1;fill:#0ff;fill-opacity:.75;fill-rule:evenodd;stroke-width:1.00157" d="M100 40v20h10v10h10v10h20V70h10V60h20v10h10v10h20V70h10V60h10V40Z" transform="scale(.26458)"/><path style="opacity:1;fill:#f95c62;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M70 10v140h10v10h40v-10h10v-10H90V10Z" transform="scale(.26458)"/>`
};
export const pixelHatAccTophat: {
  name: 'hat_acc_tophat';
  data: string;
} = {
  name: 'hat_acc_tophat',
  data: `<path style="opacity:1;fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M90 0v50h140V0ZM60 60v10h200V60Z" transform="scale(.26458)"/><path style="opacity:1;fill:red;fill-rule:evenodd;stroke-width:.264999" d="M23.813 13.23h37.041v2.645H23.813Z"/>`
};
export type headAcc =
  | 'hat_acc_beanie_blue'
  | 'hat_acc_beanie_green'
  | 'hat_acc_beanie_pink'
  | 'hat_acc_cap_blue'
  | 'hat_acc_cap_green'
  | 'hat_acc_cap_pink'
  | 'hat_acc_cowboyhat_brown'
  | 'hat_acc_cowboyhat_tan'
  | 'hat_acc_egghead'
  | 'hat_acc_gigabrain'
  | 'hat_acc_king'
  | 'hat_acc_leprechaun'
  | 'hat_acc_powderedwig'
  | 'hat_acc_snorkel_blue'
  | 'hat_acc_snorkel_green'
  | 'hat_acc_snorkel_pink'
  | 'hat_acc_tophat';
export interface MyIcon {
  name: headAcc;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];
export const completeIconSet = [
  pixelHatAccBeanieBlue,
  pixelHatAccBeanieGreen,
  pixelHatAccBeaniePink,
  pixelHatAccCapBlue,
  pixelHatAccCapGreen,
  pixelHatAccCapPink,
  pixelHatAccCowboyhatBrown,
  pixelHatAccCowboyhatTan,
  pixelHatAccEgghead,
  pixelHatAccGigabrain,
  pixelHatAccKing,
  pixelHatAccLeprechaun,
  pixelHatAccPowderedwig,
  pixelHatAccSnorkelBlue,
  pixelHatAccSnorkelGreen,
  pixelHatAccSnorkelPink,
  pixelHatAccTophat
];
