/* 🤖 this file was generated by svg-to-ts */
export const pixelHeadLooking: {
  name: 'head_looking';
  data: string;
} = {
  name: 'head_looking',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:.969766" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40Z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#fff;fill-rule:evenodd;stroke-width:1.00157" d="M130 90v30h10V90Zm50 0v30h10V90Z" transform="scale(.26458)"/><path style="fill:#000;fill-rule:evenodd;stroke-width:1.00157" d="M140 90v30h10V90Zm50 0v30h10V90Z" transform="scale(.26458)"/>`
};
export const pixelHeadOPcooly: {
  name: 'head_o_pcooly';
  data: string;
} = {
  name: 'head_o_pcooly',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40H80z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v30h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-30h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#ff0420;fill-opacity:.98823529;fill-rule:evenodd;stroke-width:1.00157" d="M100 80v20h10v10h10v10h20v-10h10v-10h20v10h10v10h20v-10h10v-10h10V80Z" transform="scale(.26458)"/><path style="fill:#fff;fill-opacity:.988235;fill-rule:evenodd;stroke-width:1.00157" d="M110 70v50h40V70h-40zm60 0v50h10v-20h30V70h-40zm-50 10h20v30h-20V80zm60 0h20v10h-20V80z" transform="scale(.26458)"/>`
};
export const pixelHeadOPeyes: {
  name: 'head_o_peyes';
  data: string;
} = {
  name: 'head_o_peyes',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40Z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#ff0420;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 90v30h30V90Zm50 0v30h30V90Z" transform="scale(.26458)"/><path style="fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 90v10h10V90Zm50 0v10h10V90Z" transform="scale(.26458)"/>`
};
export const pixelHeadOPpirate: {
  name: 'head_o_ppirate';
  data: string;
} = {
  name: 'head_o_ppirate',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40H80z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M31.75 23.813h7.938v7.938H31.75z"/><path style="fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M31.75 23.813h2.646v2.646H31.75z"/><path style="fill:#ff0420;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M100 70v10h40v10h20v30h10v10h30v-10h10V80h-60V70Zm110 10h10V70h-10z" transform="scale(.26458)"/>`
};
export const pixelHeadPlain: {
  name: 'head_plain';
  data: string;
} = {
  name: 'head_plain',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40Z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 90v30h30V90Zm50 0v30h30V90Z" transform="scale(.26458)"/><path style="fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 90v10h10V90Zm50 0v10h10V90Z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/>`
};
export const pixelHeadPoolyBot: {
  name: 'head_pooly_bot';
  data: string;
} = {
  name: 'head_pooly_bot',
  data: `<path style="fill:gray;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 50v10h10v10h10v10H70v10h10v10h20v10H60v10h10v10h20v10h10v70h120V60h-10V50H80z" transform="scale(.26458)"/><path style="fill:#404040;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M100 60v10h10V60h-10zm0 30v10h10V90h-10zm0 30v10h10v-10h-10zm40 10v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10h-50z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M170 90v30h30V90h-30zm-20 50v10h10v-10h-10zm20 0v10h10v-10h-10z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M31.75 23.813h7.938v7.938H31.75z"/><path style="fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M44.979 23.813h2.646v2.646h-2.646z"/><path style="fill:#a0a0a0;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M31.75 23.813h7.938v7.938H31.75z"/><path style="fill:red;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M34.396 26.458h2.646v2.646h-2.646z"/>`
};
export const pixelHeadPoolyCooly: {
  name: 'head_pooly_cooly';
  data: string;
} = {
  name: 'head_pooly_cooly',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40H80z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v30h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-30h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:.99;fill-rule:evenodd;stroke-width:1.00157" d="M100 80v20h10v10h10v10h20v-10h10v-10h20v10h10v10h20v-10h10v-10h10V80Z" transform="scale(.26458)"/>`
};
export const pixelHeadPoolyCrazycraw: {
  name: 'head_pooly_crazycraw';
  data: string;
} = {
  name: 'head_pooly_crazycraw',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M100 20v20h10v10H90V40H80V30H70v20h10v10h10v10h10v10H80V70H70V60H60v20h10v10h10v10h20v110h120V100h20V90h10V80h10V60h-10v10h-10v10h-20V70h10V60h10V50h10V30h-10v10h-10v10h-20V40h10V20h-10v10h-10v10h-10v10h-10V30h-10v10h-20V30h-10v20h-10V40h-10V30h-10V20h-10z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 90v30h30V90Zm50 0v30h30V90Z" transform="scale(.26458)"/><path style="fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 90v10h10V90Zm50 0v10h10V90Z" transform="scale(.26458)"/>`
};
export const pixelHeadPoolyNoun: {
  name: 'head_pooly_noun';
  data: string;
} = {
  name: 'head_pooly_noun',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40Z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:red;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157;stroke-miterlimit:4;stroke-dasharray:none" d="M120 80v20h-20v20h10v-10h10v20h40v-20h10v20h40V80h-40v20h-10V80Z" transform="scale(.26458)"/><path style="fill:#fff;fill-rule:evenodd;stroke-width:1.00157" d="M130 90v30h10V90Zm50 0v30h10V90Z" transform="scale(.26458)"/><path style="fill:#000;fill-rule:evenodd;stroke-width:1.00157" d="M140 90v30h10V90Zm50 0v30h10V90Z" transform="scale(.26458)"/>`
};
export const pixelHeadPoolyPigeon: {
  name: 'head_pooly_pigeon';
  data: string;
} = {
  name: 'head_pooly_pigeon',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:.969766" d="M130 40v10h-20v10h-10v150h120V60h-10V50h-20V40Z" transform="scale(.26458)"/><path style="fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 190v10h20v-10zm20 10v10h30v-10zm30 0h10v-10h-10z" transform="scale(.26458)"/><path style="fill:#0ff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M100 180v10h10v-10zm10 10v10h10v-10zm10 10v10h10v-10zm10 10v10h20v-10zm20 10v10h30v-10zm30 0h10v-10h-10zm10-10h10v-10h-10zm10-10h10v-10h-10zm10-10h10v-10h-10z" transform="scale(.26458)"/><path style="fill:#b200ff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M100 160v20h10v-20zm10 20v10h10v-10zm10 10v10h10v-10zm10 10v10h20v-10zm20 10v10h30v-10zm30 0h10v-10h-10zm10-10h10v-10h-10zm10-10h10v-10h-10zm10-10h10v-20h-10z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 90v30h30V90Zm50 0v30h30V90Z" transform="scale(.26458)"/>`
};
export const pixelHeadPoolyPirate: {
  name: 'head_pooly_pirate';
  data: string;
} = {
  name: 'head_pooly_pirate',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40H80z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M31.75 23.813h7.938v7.938H31.75z"/><path style="fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M31.75 23.813h2.646v2.646H31.75z"/><path style="fill:#4d4d4d;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M100 70v10h40v10h20v30h10v10h30v-10h10V80h-60V70Zm110 10h10V70h-10z" transform="scale(.26458)"/>`
};
export const pixelHeadPoolyTornadocooly: {
  name: 'head_pooly_tornadocooly';
  data: string;
} = {
  name: 'head_pooly_tornadocooly',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40H80z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v30h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-30h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#69feba;fill-opacity:.98823529;fill-rule:evenodd;stroke-width:1.00157" d="M100 80v20h10v10h10v10h20v-10h10v-10h20v10h10v10h20v-10h10v-10h10V80Z" transform="scale(.26458)"/>`
};
export const pixelHeadPoolyTornadoeyes: {
  name: 'head_pooly_tornadoeyes';
  data: string;
} = {
  name: 'head_pooly_tornadoeyes',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40H80z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#69feba;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 90v30h30V90Zm50 0v30h30V90Z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 100v10h10v-10zm50 0v10h10v-10z" transform="scale(.26458)"/>`
};
export const pixelHeadShooketh: {
  name: 'head_shooketh';
  data: string;
} = {
  name: 'head_shooketh',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 40v20h10v10h10v10H80V70H70v20h10v10h20v10H70v-10H60v20h10v10h20v10h10v70h120V60h-10V50H90V40H80z" transform="scale(.26458)"/><path style="fill:#f2a52b;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M140 130v10h-10v20h10v10h10v10h10v10h10v-10h10v-10h10v-10h10v-20h-10v-10z" transform="scale(.26458)"/><path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M150 140v10h10v-10zm20 0v10h10v-10z" transform="scale(.26458)"/><path style="fill:#fff;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M120 90v30h30V90Zm50 0v30h30V90Z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M130 100v10h10v-10zm50 0v10h10v-10z" transform="scale(.26458)"/>`
};
export type head =
  | 'head_looking'
  | 'head_o_pcooly'
  | 'head_o_peyes'
  | 'head_o_ppirate'
  | 'head_plain'
  | 'head_pooly_bot'
  | 'head_pooly_cooly'
  | 'head_pooly_crazycraw'
  | 'head_pooly_noun'
  | 'head_pooly_pigeon'
  | 'head_pooly_pirate'
  | 'head_pooly_tornadocooly'
  | 'head_pooly_tornadoeyes'
  | 'head_shooketh';
export interface MyIcon {
  name: head;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];
export const completeIconSet = [
  pixelHeadLooking,
  pixelHeadOPcooly,
  pixelHeadOPeyes,
  pixelHeadOPpirate,
  pixelHeadPlain,
  pixelHeadPoolyBot,
  pixelHeadPoolyCooly,
  pixelHeadPoolyCrazycraw,
  pixelHeadPoolyNoun,
  pixelHeadPoolyPigeon,
  pixelHeadPoolyPirate,
  pixelHeadPoolyTornadocooly,
  pixelHeadPoolyTornadoeyes,
  pixelHeadShooketh
];
