/* 🤖 this file was generated by svg-to-ts */
export const pixelLeftWingAccCane: {
  name: 'left_wing_acc_cane';
  data: string;
} = {
  name: 'left_wing_acc_cane',
  data: `<path style="fill:#00e4ff;fill-opacity:.75;fill-rule:evenodd;stroke-width:1.00157" d="M20 160v20h10v10h10v-10h10v-20z" transform="scale(.26458)"/><path style="fill-rule:evenodd;stroke-width:.264999" d="M7.938 82.02h2.645v2.647H7.937Z"/><path style="fill:#ccc;fill-rule:evenodd;stroke-width:.264999" d="M7.938 50.27h2.645v31.75H7.937Z"/>`
};
export const pixelLeftWingAccCocktail: {
  name: 'left_wing_acc_cocktail';
  data: string;
} = {
  name: 'left_wing_acc_cocktail',
  data: `<path style="fill:#0f0;fill-rule:evenodd;stroke-width:.264999" d="M13.23 18.52h2.645v2.647h-2.646z"/><path style="fill:#0f0;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M50 70v20h10V70Zm0 20H40v30h10Zm-10 30H30v20h10z" transform="scale(.26458)"/><path style="fill:#0f0;fill-rule:evenodd;stroke-width:.264999" d="M15.875 13.23h2.646v5.29h-2.646z"/><path style="fill:#f2a52b;fill-opacity:.72;fill-rule:evenodd;stroke-width:1.00157" d="M30 80v20H20v40h10v10h30v-10h10v-40H60V80Z" transform="scale(.26458)"/><path style="fill:#784421;fill-rule:evenodd;stroke-width:.264999" d="M10.583 18.52h2.646v5.293h-2.646z"/><path style="fill:#fff;fill-opacity:.57;fill-rule:evenodd;stroke-width:1.00157" d="M20 70v30H10v40h10v10h10v10h10v20H30v10H20v10h50v-10H60v-10H50v-20h10v-10h10v-10h10v-40H70V70Z" transform="scale(.26458)"/><path style="fill:#fff;fill-opacity:.57;fill-rule:evenodd;stroke-width:.264999" d="M2.646 18.52h18.52v2.647H2.647Z"/><path style="fill:#fff;fill-opacity:.57;fill-rule:evenodd;stroke-width:1.00157" d="M10 70v10h10V70Zm60 0v10h10V70Z" transform="scale(.26458)"/><path style="fill:#784421;fill-rule:evenodd;stroke-width:.264999" d="M7.938 15.875h2.645v2.646H7.937Z"/><path style="fill:#f0f;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M20 40v10H10v20h10V60h10V50h10V40H30Z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccDefendershield: {
  name: 'left_wing_acc_defendershield';
  data: string;
} = {
  name: 'left_wing_acc_defendershield',
  data: `<path style="fill:#b3b3b3;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M30 150v10H20v10H0v50h10v30h10v20h10v20h10v10h10v-10h10v-20h10v-20h10v-30h10v-50H70v-10H60v-10z" transform="scale(.26458)"/><path style="fill:#404040;fill-rule:evenodd;stroke-width:1.00157;fill-opacity:1" d="M20 180v60h40v-10H40v-40h20v-10H20zm40 10v40h10v-40H60z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccGavel: {
  name: 'left_wing_acc_gavel';
  data: string;
} = {
  name: 'left_wing_acc_gavel',
  data: `<path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M0 110v40h30v70h20v-70h30v-10h10v-20H80v-10H30Z" transform="scale(.26458)"/><path style="fill:#ffd800;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M10 110v40h10v-40zm50 0v40h10v-40z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccNoodleBlue: {
  name: 'left_wing_acc_noodle_blue';
  data: string;
} = {
  name: 'left_wing_acc_noodle_blue',
  data: `<path style="fill:#3b5cf7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M40 100v10H30v10H20v50h10v40h10v40H30v40H20v10h30v-40h10v-60H50v-40H40v-30h10v-10h10v-10h10v-10H60Z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccNoodleGreen: {
  name: 'left_wing_acc_noodle_green';
  data: string;
} = {
  name: 'left_wing_acc_noodle_green',
  data: `<path style="fill:#00c900;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M40 100v10H30v10H20v50h10v40h10v40H30v40H20v10h30v-40h10v-60H50v-40H40v-30h10v-10h10v-10h10v-10H60Z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccNoodlePink: {
  name: 'left_wing_acc_noodle_pink';
  data: string;
} = {
  name: 'left_wing_acc_noodle_pink',
  data: `<path style="fill:#ff757c;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M40 100v10H30v10H20v50h10v40h10v40H30v40H20v10h30v-40h10v-60H50v-40H40v-30h10v-10h10v-10h10v-10H60Z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccTornadoshield: {
  name: 'left_wing_acc_tornadoshield';
  data: string;
} = {
  name: 'left_wing_acc_tornadoshield',
  data: `<path style="fill:#666;fill-opacity:1;fill-rule:evenodd;stroke-width:.500784" d="M0 170v30h10v10H0v10h10v10h10v10h10v10H10v10h10v10h10v10h10v10h10v10H40v20h10v-10h10v-10h10v-10h10v-10H70v-10h10v-10h10v-10h10v-10H90v-10H70v-10h10v-10h10v-10h10v-10h10v-10h10v-10H0z" transform="scale(.26458)"/><path style="fill:#333;fill-rule:evenodd;stroke-width:1.00157" d="M10 190v10h20v-10H10zm20 10v10h30v-10H30zm30 10v10h10v-10H60zm-30 20v10h20v-10H30zm20 10v10h20v-10H50zm20 10v10h10v-10H70zm-30 20v10h20v-10H40zm20 10v10h10v-10H60z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccTrophy: {
  name: 'left_wing_acc_trophy';
  data: string;
} = {
  name: 'left_wing_acc_trophy',
  data: `<path style="fill:#782121;fill-rule:evenodd;stroke-width:.264999" d="M5.292 50.27H18.52v2.647H5.29Z"/><path style="fill:#ffd800;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M20 120v30h10v10h10v20H30v10h30v-10H50v-20h10v-10h10v-30z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccUmbrellaBlue: {
  name: 'left_wing_acc_umbrella_blue';
  data: string;
} = {
  name: 'left_wing_acc_umbrella_blue',
  data: `<path style="fill:#3b5cf7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M20 230v70h10v20h10v-20h10v-70z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M40 180v10h20v-10zm20 10v10h10v-10zm-20 0H30v50h10z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccUmbrellaGreen: {
  name: 'left_wing_acc_umbrella_green';
  data: string;
} = {
  name: 'left_wing_acc_umbrella_green',
  data: `<path style="fill:#00c900;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M20 230v70h10v20h10v-20h10v-70z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M40 180v10h20v-10zm20 10v10h10v-10zm-20 0H30v50h10z" transform="scale(.26458)"/>`
};
export const pixelLeftWingAccUmbrellaPink: {
  name: 'left_wing_acc_umbrella_pink';
  data: string;
} = {
  name: 'left_wing_acc_umbrella_pink',
  data: `<path style="fill:#ff757c;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M20 230v70h10v20h10v-20h10v-70z" transform="scale(.26458)"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M40 180v10h20v-10zm20 10v10h10v-10zm-20 0H30v50h10z" transform="scale(.26458)"/>`
};
export type leftAcc =
  | 'left_wing_acc_cane'
  | 'left_wing_acc_cocktail'
  | 'left_wing_acc_defendershield'
  | 'left_wing_acc_gavel'
  | 'left_wing_acc_noodle_blue'
  | 'left_wing_acc_noodle_green'
  | 'left_wing_acc_noodle_pink'
  | 'left_wing_acc_tornadoshield'
  | 'left_wing_acc_trophy'
  | 'left_wing_acc_umbrella_blue'
  | 'left_wing_acc_umbrella_green'
  | 'left_wing_acc_umbrella_pink';
export interface MyIcon {
  name: leftAcc;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];
export const completeIconSet = [
  pixelLeftWingAccCane,
  pixelLeftWingAccCocktail,
  pixelLeftWingAccDefendershield,
  pixelLeftWingAccGavel,
  pixelLeftWingAccNoodleBlue,
  pixelLeftWingAccNoodleGreen,
  pixelLeftWingAccNoodlePink,
  pixelLeftWingAccTornadoshield,
  pixelLeftWingAccTrophy,
  pixelLeftWingAccUmbrellaBlue,
  pixelLeftWingAccUmbrellaGreen,
  pixelLeftWingAccUmbrellaPink
];
