/* 🤖 this file was generated by svg-to-ts */
export const pixelLeftWing: {
  name: 'left_wing';
  data: string;
} = {
  name: 'left_wing',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M20 180v20h10v20h10v40h20v30h30v-90H60v-10H30v-10z" transform="scale(.26458)"/><path style="fill:#341762;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M10 180v10h10v-10zm10 20v10h10v-10zm10 20v20h10v-20zm20 20v30h10v-30zm20 10v50h10v-50z" transform="scale(.26458)"/>`
};
export const pixelLeftWingrobo: {
  name: 'left_wingrobo';
  data: string;
} = {
  name: 'left_wingrobo',
  data: `<path style="fill:gray;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M20 180v20h10v20h10v40h20v30h30v-90H60v-10H30v-10z" transform="scale(.26458)"/><path style="fill:#404040;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M10 180v10h10v-10zm10 20v10h10v-10zm10 20v20h10v-20zm20 20v30h10v-30zm20 10v50h10v-50z" transform="scale(.26458)"/>`
};
export const pixelLeftWingtucked: {
  name: 'left_wingtucked';
  data: string;
} = {
  name: 'left_wingtucked',
  data: `<path style="fill:#341762;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 200v10h20v-10H80zm20 10v10h10v-10h-10zm-20 0H70v30h10v-30zm-10 30H60v50h10v-50zm0 50v10h10v-10H70zm10 0h10v-20H80v20zm10-20h10v-20H90v20z" transform="scale(.26458)"/><path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M80 210v30H70v50h10v-20h10v-20h10v-40H80z" transform="scale(.26458)"/>`
};
export type left = 'left_wing' | 'left_wingrobo' | 'left_wingtucked';
export interface MyIcon {
  name: left;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];
export const completeIconSet = [
  pixelLeftWing,
  pixelLeftWingrobo,
  pixelLeftWingtucked
];
