/* 🤖 this file was generated by svg-to-ts */
export const pixelRightWingAccCane: {
  name: 'right_wing_acc_cane';
  data: string;
} = {
  name: 'right_wing_acc_cane',
  data: `<path style="fill:#00e4ff;fill-opacity:.75;fill-rule:evenodd;stroke-width:.264999" d="M79.375 42.333v5.292h-2.646v2.646h-2.646v-2.646h-2.646v-5.292z"/><path style="fill-rule:evenodd;stroke-width:.264999" d="M76.73 82.02h-2.647v2.647h2.646z"/><path style="fill:#ccc;fill-rule:evenodd;stroke-width:.264999" d="M76.73 50.27h-2.647v31.75h2.646z"/>`
};
export const pixelRightWingAccCocktail: {
  name: 'right_wing_acc_cocktail';
  data: string;
} = {
  name: 'right_wing_acc_cocktail',
  data: `<path style="fill:#0f0;fill-rule:evenodd;stroke-width:.264999" d="M71.437 18.52h-2.645v2.647h2.645z"/><path style="fill:#0f0;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M71.437 18.52v5.293h-2.645V18.52zm0 5.293h2.646v7.937h-2.646zm2.646 7.937h2.646v5.292h-2.646z"/><path style="fill:#0f0;fill-rule:evenodd;stroke-width:.264999" d="M68.792 13.23h-2.646v5.29h2.646z"/><path style="fill:#f2a52b;fill-opacity:.72;fill-rule:evenodd;stroke-width:.264999" d="M76.73 21.167v5.291h2.645v10.584h-2.646v2.645h-7.937v-2.645h-2.646V26.458h2.646v-5.291z"/><path style="fill:#784421;fill-rule:evenodd;stroke-width:.264999" d="M74.083 18.52h-2.646v5.293h2.646z"/><path style="fill:#fff;fill-opacity:.57;fill-rule:evenodd;stroke-width:.264999" d="M79.375 18.52v7.938h2.646v10.584h-2.646v2.645h-2.646v2.646h-2.646v5.292h2.646v2.646h2.646v2.646h-13.23V50.27h2.647v-2.646h2.645v-5.292h-2.645v-2.645h-2.646v-2.646H63.5V26.458h2.646v-7.937z"/><path style="fill:#fff;fill-opacity:.57;fill-rule:evenodd;stroke-width:.264999" d="M82.02 18.52H63.5v2.647h18.52z"/><path style="fill:#fff;fill-opacity:.57;fill-rule:evenodd;stroke-width:.264999" d="M82.02 18.52v2.647h-2.645V18.52zm-15.874 0v2.647H63.5V18.52z"/><path style="fill:#784421;fill-rule:evenodd;stroke-width:.264999" d="M76.73 15.875h-2.647v2.646h2.646z"/><path style="fill:#f0f;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M79.375 10.583v2.646h2.646v5.292h-2.646v-2.646h-2.646v-2.646h-2.646v-2.646h2.646z"/>`
};
export const pixelRightWingAccDefendershield: {
  name: 'right_wing_acc_defendershield';
  data: string;
} = {
  name: 'right_wing_acc_defendershield',
  data: `<path style="fill:#b3b3b3;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M76.73 39.688v2.645h2.645v2.646h5.292v13.23H82.02v7.937h-2.646v5.291h-2.646v5.292h-2.646v2.646h-2.646v-2.646h-2.645v-5.292h-2.646v-5.291H63.5v-7.938h-2.646V44.98h5.292v-2.646h2.646v-2.645Z"/><path style="fill:#404040;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M66.146 47.625V63.5h10.583v-2.646h-5.291V50.271h5.291v-2.646h-5.291Zm10.583 2.646v10.583h2.646V50.271Z"/>`
};
export const pixelRightWingAccGavel: {
  name: 'right_wing_acc_gavel';
  data: string;
} = {
  name: 'right_wing_acc_gavel',
  data: `<path style="fill:#7f3300;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M84.667 29.104v10.584h-7.938v18.52h-5.292v-18.52H63.5v-2.646h-2.646V31.75H63.5v-2.646h13.229z"/><path style="fill:#ffd800;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M82.02 29.104v10.584h-2.645V29.104Zm-13.228 0v10.584h-2.646V29.104Z"/>`
};
export const pixelRightWingAccNoodleBlue: {
  name: 'right_wing_acc_noodle_blue';
  data: string;
} = {
  name: 'right_wing_acc_noodle_blue',
  data: `<path style="fill:#3b5cf7;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M74.083 26.458v2.646h2.646v2.646h2.646v13.23h-2.646v10.582h-2.646v10.584h2.646v10.583h2.646v2.646h-7.937V68.792h-2.646V52.917h2.646V42.333h2.645v-7.937h-2.645V31.75h-2.646v-2.646h-2.646v-2.646h2.646z"/>`
};
export const pixelRightWingAccNoodleGreen: {
  name: 'right_wing_acc_noodle_green';
  data: string;
} = {
  name: 'right_wing_acc_noodle_green',
  data: `<path style="fill:#00c900;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M74.083 26.458v2.646h2.646v2.646h2.646v13.23h-2.646v10.582h-2.646v10.584h2.646v10.583h2.646v2.646h-7.937V68.792h-2.646V52.917h2.646V42.333h2.645v-7.937h-2.645V31.75h-2.646v-2.646h-2.646v-2.646h2.646z"/>`
};
export const pixelRightWingAccNoodlePink: {
  name: 'right_wing_acc_noodle_pink';
  data: string;
} = {
  name: 'right_wing_acc_noodle_pink',
  data: `<path style="fill:#ff757c;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M74.083 26.458v2.646h2.646v2.646h2.646v13.23h-2.646v10.582h-2.646v10.584h2.646v10.583h2.646v2.646h-7.938V68.792h-2.645V52.917h2.645V42.333h2.646v-7.937h-2.646V31.75h-2.645v-2.646h-2.646v-2.646h2.646z"/>`
};
export const pixelRightWingAccTornadoshield: {
  name: 'right_wing_acc_tornadoshield';
  data: string;
} = {
  name: 'right_wing_acc_tornadoshield',
  data: `<path style="fill:#666;fill-opacity:1;fill-rule:evenodd;stroke-width:.500784" d="M200 170v10h10v10h10v10h10v10h-10v10h10v10h10v10h10v10h-20v10h10v10h10v10h10v10h10v10h-10v20h10v-10h10v-10h10v-10h10v-10h-10v-10h10v-10h10v-10h10v-10h-10v-10h-20v-10h10v-10h10v-10h10v-30H200z" transform="scale(.26458)"/><path style="fill:#333;fill-rule:evenodd;stroke-width:.264999" d="M60.854 50.27v2.647h5.292V50.27zm5.292 2.647v2.645h7.937v-2.645zm7.937 2.645v2.646h2.646v-2.646zm-7.937 5.292V63.5h5.291v-2.646zm5.291 2.646v2.646h5.292V63.5zm5.292 2.646v2.646h2.646v-2.646zm-7.937 5.291v2.646h5.291v-2.646zm5.291 2.646v2.646h2.646v-2.646z"/>`
};
export const pixelRightWingAccTrophy: {
  name: 'right_wing_acc_trophy';
  data: string;
} = {
  name: 'right_wing_acc_trophy',
  data: `<path style="fill:#782121;fill-rule:evenodd;stroke-width:.264999" d="M79.375 50.27h-13.23v2.647h13.23z"/><path style="fill:#ffd800;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M79.375 31.75v7.938h-2.646v2.645h-2.646v5.292h2.646v2.646h-7.937v-2.646h2.645v-5.292h-2.645v-2.645h-2.646V31.75Z"/>`
};
export const pixelRightWingAccUmbrellaBlue: {
  name: 'right_wing_acc_umbrella_blue';
  data: string;
} = {
  name: 'right_wing_acc_umbrella_blue',
  data: `<path style="fill:#3b5cf7;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M79.375 60.854v18.521h-2.646v5.292h-2.646v-5.292h-2.645v-18.52Z"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M74.083 47.625v2.646h-5.291v-2.646zm-5.291 2.646v2.646h-2.646V50.27zm5.291 0h2.646V63.5h-2.646z"/>`
};
export const pixelRightWingAccUmbrellaGreen: {
  name: 'right_wing_acc_umbrella_green';
  data: string;
} = {
  name: 'right_wing_acc_umbrella_green',
  data: `<path style="fill:#00c900;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M79.375 60.854v18.521h-2.646v5.292h-2.646v-5.292h-2.645v-18.52Z"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M74.083 47.625v2.646h-5.291v-2.646zm-5.291 2.646v2.646h-2.646V50.27zm5.291 0h2.646V63.5h-2.646z"/>`
};
export const pixelRightWingAccUmbrellaPink: {
  name: 'right_wing_acc_umbrella_pink';
  data: string;
} = {
  name: 'right_wing_acc_umbrella_pink',
  data: `<path style="fill:#ff757c;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M79.375 60.854v18.521h-2.646v5.292h-2.646v-5.292h-2.646v-18.52Z"/><path style="fill:#000;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M74.083 47.625v2.646h-5.291v-2.646zm-5.291 2.646v2.646h-2.646V50.27zm5.291 0h2.646V63.5h-2.646z"/>`
};
export type rightAcc =
  | 'right_wing_acc_cane'
  | 'right_wing_acc_cocktail'
  | 'right_wing_acc_defendershield'
  | 'right_wing_acc_gavel'
  | 'right_wing_acc_noodle_blue'
  | 'right_wing_acc_noodle_green'
  | 'right_wing_acc_noodle_pink'
  | 'right_wing_acc_tornadoshield'
  | 'right_wing_acc_trophy'
  | 'right_wing_acc_umbrella_blue'
  | 'right_wing_acc_umbrella_green'
  | 'right_wing_acc_umbrella_pink';
export interface MyIcon {
  name: rightAcc;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];
export const completeIconSet = [
  pixelRightWingAccCane,
  pixelRightWingAccCocktail,
  pixelRightWingAccDefendershield,
  pixelRightWingAccGavel,
  pixelRightWingAccNoodleBlue,
  pixelRightWingAccNoodleGreen,
  pixelRightWingAccNoodlePink,
  pixelRightWingAccTornadoshield,
  pixelRightWingAccTrophy,
  pixelRightWingAccUmbrellaBlue,
  pixelRightWingAccUmbrellaGreen,
  pixelRightWingAccUmbrellaPink
];
