/* 🤖 this file was generated by svg-to-ts */
export const pixelRightWing: {
  name: 'right_wing';
  data: string;
} = {
  name: 'right_wing',
  data: `<path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M79.375 47.625v5.292h-2.646v5.291h-2.646v10.584h-5.291v7.937h-7.938V52.917h7.938V50.27h7.937v-2.646z"/><path style="fill:#341762;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M82.02 47.625v2.646h-2.645v-2.646zm-2.645 5.292v2.645h-2.646v-2.645zm-2.646 5.291V63.5h-2.646v-5.292zM71.437 63.5v7.937h-2.645V63.5zm-5.291 2.646v13.229H63.5v-13.23Z"/>`
};
export const pixelRightWingrobo: {
  name: 'right_wingrobo';
  data: string;
} = {
  name: 'right_wingrobo',
  data: `<path style="fill:gray;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M79.375 47.625v5.292h-2.646v5.291h-2.646v10.584h-5.291v7.937h-7.938V52.917h7.938V50.27h7.937v-2.646z"/><path style="fill:#404040;fill-opacity:1;fill-rule:evenodd;stroke-width:.264999" d="M82.02 47.625v2.646h-2.645v-2.646zm-2.645 5.292v2.645h-2.646v-2.645zm-2.646 5.291V63.5h-2.646v-5.292zM71.437 63.5v7.937h-2.645V63.5zm-5.291 2.646v13.229H63.5v-13.23Z"/>`
};
export const pixelRightWingtucked: {
  name: 'right_wingtucked';
  data: string;
} = {
  name: 'right_wingtucked',
  data: `<path style="fill:#341762;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M220 200v10h20v-10h-20zm20 10v30h10v-30h-10zm10 30v50h10v-50h-10zm0 50h-10v10h10v-10zm-10 0v-20h-10v20h10zm-10-20v-20h-10v20h10zm-10-60h-10v10h10v-10z" transform="scale(.26458)"/><path style="fill:#5227a7;fill-opacity:1;fill-rule:evenodd;stroke-width:1.00157" d="M220 210v40h10v20h10v20h10v-50h-10v-30h-20z" transform="scale(.26458)"/>`
};
export type right = 'right_wing' | 'right_wingrobo' | 'right_wingtucked';
export interface MyIcon {
  name: right;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];
export const completeIconSet = [
  pixelRightWing,
  pixelRightWingrobo,
  pixelRightWingtucked
];
